// Generated by `rindle schema gen` from the daemon's introspected schema (GET /schema).
// Do not edit by hand — re-run the generator after each migration.
//
// Column kinds come from your declared SQL types: TEXT maps to string(), INTEGER/REAL to
// number(), and a column declared BOOLEAN/BOOL or JSON to boolean()/json(). Nullability comes from
// the SQL too: a nullable column is string().nullable() (typed T | null), a NOT NULL column is bare
// string(), and PK columns are always non-null. The only thing the SQL can't carry is a refinement
// *within* a kind — the element type of json<T>(), or a string/number literal union — declare those
// ONCE in a hand-written module with refineTable(...) + refineSchema(...); they survive every regen
// of this file.

import { createSchema, number, string, table } from "@rindle/client";

export const message = table("message")
  .columns({
    id: string(),
    roomId: string(),
    author: string(),
    body: string(),
    createdAt: number(),
  })
  .primaryKey("id");

export const post = table("post")
  .columns({
    id: string(),
    title: string(),
    date: string().nullable(),
    publishedAt: number(),
    description: string(),
    tags: string(),
    concern: string(),
    author: string(),
    form: string().nullable(),
    kind: string().nullable(),
    image: string().nullable(),
    html: string(),
    body: string(),
  })
  .primaryKey("id");

export const room = table("room")
  .columns({
    id: string(),
    name: string(),
    createdAt: number(),
  })
  .primaryKey("id");

export const schema = createSchema({ tables: [message, post, room] });
