// Generated by `rindle schema gen` from the daemon's introspected schema (GET /schema).
// Do not edit by hand — re-run the generator after each migration.
//
// Column kinds come from your declared SQL types: TEXT maps to string(), INTEGER/REAL to
// number(), and a column declared BOOLEAN/BOOL or JSON to boolean()/json(). Nullability comes from
// the SQL too: a nullable column is string().nullable() (typed T | null), a NOT NULL column is bare
// string(), and PK columns are always non-null. The only thing the SQL can't carry is a refinement
// *within* a kind — the element type of json<T>(), or a string/number literal union — declare those
// ONCE in a hand-written module with refineTable(...) + refineSchema(...); they survive every regen
// of this file.

import { createSchema, number, string, table } from "@rindle/client";

export const author = table("author")
  .columns({
    id: string(),
    displayName: string(),
    glyph: string().nullable(),
    color: string().nullable(),
  })
  .primaryKey("id");

export const post = table("post")
  .columns({
    id: string(),
    title: string(),
    date: string().nullable(),
    publishedAt: number(),
    description: string(),
    tags: string(),
    concern: string(),
    author: string(),
    form: string().nullable(),
    kind: string().nullable(),
    image: string().nullable(),
    html: string(),
    body: string(),
    cardImage: string().nullable(),
    pinned: number(),
    readingMinutes: number(),
    color: string().nullable(),
    contentRevision: string(),
    colorRevision: string().nullable(),
    colorProjectionVersion: string().nullable(),
    colorStatus: string(),
  })
  .primaryKey("id");

export const postAuthor = table("postAuthor")
  .columns({
    id: string(),
    postId: string(),
    authorId: string(),
    position: number(),
  })
  .primaryKey("id");

export const postFacet = table("postFacet")
  .columns({
    id: string(),
    postId: string(),
    facet: string(),
    value: string(),
    position: number(),
  })
  .primaryKey("id");

export const schema = createSchema({ tables: [author, post, postAuthor, postFacet] });
