/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TasksRouteImport } from './routes/tasks'
import { Route as QuestionsRouteImport } from './routes/questions'
import { Route as MusicRouteImport } from './routes/music'
import { Route as MoviesRouteImport } from './routes/movies'
import { Route as MediaRouteImport } from './routes/media'
import { Route as LocationsRouteImport } from './routes/locations'
import { Route as GraphRouteImport } from './routes/graph'
import { Route as FramingsRouteImport } from './routes/framings'
import { Route as EventsRouteImport } from './routes/events'
import { Route as CaptureRouteImport } from './routes/capture'
import { Route as BooksRouteImport } from './routes/books'
import { Route as BookmarksRouteImport } from './routes/bookmarks'
import { Route as AmplificationsRouteImport } from './routes/amplifications'
import { Route as DocumentsRouteImport } from './routes/_documents'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TIdRouteImport } from './routes/t.$id'
import { Route as FramingsIdRouteImport } from './routes/framings_.$id'
import { Route as DocumentsDocumentsRouteImport } from './routes/_documents.documents'
import { Route as DocumentsDocumentsNewRouteImport } from './routes/_documents.documents_.new'
import { Route as DocumentsDocumentsIdRouteImport } from './routes/_documents.documents_.$id'

const TasksRoute = TasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => rootRouteImport,
} as any)
const QuestionsRoute = QuestionsRouteImport.update({
  id: '/questions',
  path: '/questions',
  getParentRoute: () => rootRouteImport,
} as any)
const MusicRoute = MusicRouteImport.update({
  id: '/music',
  path: '/music',
  getParentRoute: () => rootRouteImport,
} as any)
const MoviesRoute = MoviesRouteImport.update({
  id: '/movies',
  path: '/movies',
  getParentRoute: () => rootRouteImport,
} as any)
const MediaRoute = MediaRouteImport.update({
  id: '/media',
  path: '/media',
  getParentRoute: () => rootRouteImport,
} as any)
const LocationsRoute = LocationsRouteImport.update({
  id: '/locations',
  path: '/locations',
  getParentRoute: () => rootRouteImport,
} as any)
const GraphRoute = GraphRouteImport.update({
  id: '/graph',
  path: '/graph',
  getParentRoute: () => rootRouteImport,
} as any)
const FramingsRoute = FramingsRouteImport.update({
  id: '/framings',
  path: '/framings',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsRoute = EventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => rootRouteImport,
} as any)
const CaptureRoute = CaptureRouteImport.update({
  id: '/capture',
  path: '/capture',
  getParentRoute: () => rootRouteImport,
} as any)
const BooksRoute = BooksRouteImport.update({
  id: '/books',
  path: '/books',
  getParentRoute: () => rootRouteImport,
} as any)
const BookmarksRoute = BookmarksRouteImport.update({
  id: '/bookmarks',
  path: '/bookmarks',
  getParentRoute: () => rootRouteImport,
} as any)
const AmplificationsRoute = AmplificationsRouteImport.update({
  id: '/amplifications',
  path: '/amplifications',
  getParentRoute: () => rootRouteImport,
} as any)
const DocumentsRoute = DocumentsRouteImport.update({
  id: '/_documents',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TIdRoute = TIdRouteImport.update({
  id: '/t/$id',
  path: '/t/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const FramingsIdRoute = FramingsIdRouteImport.update({
  id: '/framings_/$id',
  path: '/framings/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const DocumentsDocumentsRoute = DocumentsDocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => DocumentsRoute,
} as any)
const DocumentsDocumentsNewRoute = DocumentsDocumentsNewRouteImport.update({
  id: '/documents_/new',
  path: '/documents/new',
  getParentRoute: () => DocumentsRoute,
} as any)
const DocumentsDocumentsIdRoute = DocumentsDocumentsIdRouteImport.update({
  id: '/documents_/$id',
  path: '/documents/$id',
  getParentRoute: () => DocumentsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/amplifications': typeof AmplificationsRoute
  '/bookmarks': typeof BookmarksRoute
  '/books': typeof BooksRoute
  '/capture': typeof CaptureRoute
  '/events': typeof EventsRoute
  '/framings': typeof FramingsRoute
  '/graph': typeof GraphRoute
  '/locations': typeof LocationsRoute
  '/media': typeof MediaRoute
  '/movies': typeof MoviesRoute
  '/music': typeof MusicRoute
  '/questions': typeof QuestionsRoute
  '/tasks': typeof TasksRoute
  '/documents': typeof DocumentsDocumentsRoute
  '/framings/$id': typeof FramingsIdRoute
  '/t/$id': typeof TIdRoute
  '/documents/$id': typeof DocumentsDocumentsIdRoute
  '/documents/new': typeof DocumentsDocumentsNewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/amplifications': typeof AmplificationsRoute
  '/bookmarks': typeof BookmarksRoute
  '/books': typeof BooksRoute
  '/capture': typeof CaptureRoute
  '/events': typeof EventsRoute
  '/framings': typeof FramingsRoute
  '/graph': typeof GraphRoute
  '/locations': typeof LocationsRoute
  '/media': typeof MediaRoute
  '/movies': typeof MoviesRoute
  '/music': typeof MusicRoute
  '/questions': typeof QuestionsRoute
  '/tasks': typeof TasksRoute
  '/documents': typeof DocumentsDocumentsRoute
  '/framings/$id': typeof FramingsIdRoute
  '/t/$id': typeof TIdRoute
  '/documents/$id': typeof DocumentsDocumentsIdRoute
  '/documents/new': typeof DocumentsDocumentsNewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_documents': typeof DocumentsRouteWithChildren
  '/amplifications': typeof AmplificationsRoute
  '/bookmarks': typeof BookmarksRoute
  '/books': typeof BooksRoute
  '/capture': typeof CaptureRoute
  '/events': typeof EventsRoute
  '/framings': typeof FramingsRoute
  '/graph': typeof GraphRoute
  '/locations': typeof LocationsRoute
  '/media': typeof MediaRoute
  '/movies': typeof MoviesRoute
  '/music': typeof MusicRoute
  '/questions': typeof QuestionsRoute
  '/tasks': typeof TasksRoute
  '/_documents/documents': typeof DocumentsDocumentsRoute
  '/framings_/$id': typeof FramingsIdRoute
  '/t/$id': typeof TIdRoute
  '/_documents/documents_/$id': typeof DocumentsDocumentsIdRoute
  '/_documents/documents_/new': typeof DocumentsDocumentsNewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/amplifications'
    | '/bookmarks'
    | '/books'
    | '/capture'
    | '/events'
    | '/framings'
    | '/graph'
    | '/locations'
    | '/media'
    | '/movies'
    | '/music'
    | '/questions'
    | '/tasks'
    | '/documents'
    | '/framings/$id'
    | '/t/$id'
    | '/documents/$id'
    | '/documents/new'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/amplifications'
    | '/bookmarks'
    | '/books'
    | '/capture'
    | '/events'
    | '/framings'
    | '/graph'
    | '/locations'
    | '/media'
    | '/movies'
    | '/music'
    | '/questions'
    | '/tasks'
    | '/documents'
    | '/framings/$id'
    | '/t/$id'
    | '/documents/$id'
    | '/documents/new'
  id:
    | '__root__'
    | '/'
    | '/_documents'
    | '/amplifications'
    | '/bookmarks'
    | '/books'
    | '/capture'
    | '/events'
    | '/framings'
    | '/graph'
    | '/locations'
    | '/media'
    | '/movies'
    | '/music'
    | '/questions'
    | '/tasks'
    | '/_documents/documents'
    | '/framings_/$id'
    | '/t/$id'
    | '/_documents/documents_/$id'
    | '/_documents/documents_/new'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DocumentsRoute: typeof DocumentsRouteWithChildren
  AmplificationsRoute: typeof AmplificationsRoute
  BookmarksRoute: typeof BookmarksRoute
  BooksRoute: typeof BooksRoute
  CaptureRoute: typeof CaptureRoute
  EventsRoute: typeof EventsRoute
  FramingsRoute: typeof FramingsRoute
  GraphRoute: typeof GraphRoute
  LocationsRoute: typeof LocationsRoute
  MediaRoute: typeof MediaRoute
  MoviesRoute: typeof MoviesRoute
  MusicRoute: typeof MusicRoute
  QuestionsRoute: typeof QuestionsRoute
  TasksRoute: typeof TasksRoute
  FramingsIdRoute: typeof FramingsIdRoute
  TIdRoute: typeof TIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tasks': {
      id: '/tasks'
      path: '/tasks'
      fullPath: '/tasks'
      preLoaderRoute: typeof TasksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/questions': {
      id: '/questions'
      path: '/questions'
      fullPath: '/questions'
      preLoaderRoute: typeof QuestionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/music': {
      id: '/music'
      path: '/music'
      fullPath: '/music'
      preLoaderRoute: typeof MusicRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/movies': {
      id: '/movies'
      path: '/movies'
      fullPath: '/movies'
      preLoaderRoute: typeof MoviesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/media': {
      id: '/media'
      path: '/media'
      fullPath: '/media'
      preLoaderRoute: typeof MediaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/locations': {
      id: '/locations'
      path: '/locations'
      fullPath: '/locations'
      preLoaderRoute: typeof LocationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/graph': {
      id: '/graph'
      path: '/graph'
      fullPath: '/graph'
      preLoaderRoute: typeof GraphRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/framings': {
      id: '/framings'
      path: '/framings'
      fullPath: '/framings'
      preLoaderRoute: typeof FramingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events': {
      id: '/events'
      path: '/events'
      fullPath: '/events'
      preLoaderRoute: typeof EventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/capture': {
      id: '/capture'
      path: '/capture'
      fullPath: '/capture'
      preLoaderRoute: typeof CaptureRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/books': {
      id: '/books'
      path: '/books'
      fullPath: '/books'
      preLoaderRoute: typeof BooksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bookmarks': {
      id: '/bookmarks'
      path: '/bookmarks'
      fullPath: '/bookmarks'
      preLoaderRoute: typeof BookmarksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/amplifications': {
      id: '/amplifications'
      path: '/amplifications'
      fullPath: '/amplifications'
      preLoaderRoute: typeof AmplificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_documents': {
      id: '/_documents'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof DocumentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/t/$id': {
      id: '/t/$id'
      path: '/t/$id'
      fullPath: '/t/$id'
      preLoaderRoute: typeof TIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/framings_/$id': {
      id: '/framings_/$id'
      path: '/framings/$id'
      fullPath: '/framings/$id'
      preLoaderRoute: typeof FramingsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_documents/documents': {
      id: '/_documents/documents'
      path: '/documents'
      fullPath: '/documents'
      preLoaderRoute: typeof DocumentsDocumentsRouteImport
      parentRoute: typeof DocumentsRoute
    }
    '/_documents/documents_/new': {
      id: '/_documents/documents_/new'
      path: '/documents/new'
      fullPath: '/documents/new'
      preLoaderRoute: typeof DocumentsDocumentsNewRouteImport
      parentRoute: typeof DocumentsRoute
    }
    '/_documents/documents_/$id': {
      id: '/_documents/documents_/$id'
      path: '/documents/$id'
      fullPath: '/documents/$id'
      preLoaderRoute: typeof DocumentsDocumentsIdRouteImport
      parentRoute: typeof DocumentsRoute
    }
  }
}

interface DocumentsRouteChildren {
  DocumentsDocumentsRoute: typeof DocumentsDocumentsRoute
  DocumentsDocumentsIdRoute: typeof DocumentsDocumentsIdRoute
  DocumentsDocumentsNewRoute: typeof DocumentsDocumentsNewRoute
}

const DocumentsRouteChildren: DocumentsRouteChildren = {
  DocumentsDocumentsRoute: DocumentsDocumentsRoute,
  DocumentsDocumentsIdRoute: DocumentsDocumentsIdRoute,
  DocumentsDocumentsNewRoute: DocumentsDocumentsNewRoute,
}

const DocumentsRouteWithChildren = DocumentsRoute._addFileChildren(
  DocumentsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DocumentsRoute: DocumentsRouteWithChildren,
  AmplificationsRoute: AmplificationsRoute,
  BookmarksRoute: BookmarksRoute,
  BooksRoute: BooksRoute,
  CaptureRoute: CaptureRoute,
  EventsRoute: EventsRoute,
  FramingsRoute: FramingsRoute,
  GraphRoute: GraphRoute,
  LocationsRoute: LocationsRoute,
  MediaRoute: MediaRoute,
  MoviesRoute: MoviesRoute,
  MusicRoute: MusicRoute,
  QuestionsRoute: QuestionsRoute,
  TasksRoute: TasksRoute,
  FramingsIdRoute: FramingsIdRoute,
  TIdRoute: TIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
