packages:
  - packages/facets
  - packages/compiler
  - packages/frontend
  - packages/editor
  - packages/thoughts
  - packages/lists
  - packages/comments
  - packages/server
  - packages/dha-report-app
  - worker

onlyBuiltDependencies:
  - sharp
  - workerd

onlyBuiltDependenciesFile: ''
