packages:
  - packages/compiler
  - packages/frontend
  - packages/thoughts
  - packages/server
  - packages/dha-report-app
  - packages/posts
  - worker

onlyBuiltDependencies:
  - sharp
  - workerd

onlyBuiltDependenciesFile: ''
