-- Groundwork for live-authored posts.
--
-- `color` is a materialized semantic color: external enrichment may compute it from an embedding,
-- but subscriptions only need this small renderable result. The revision columns let an enricher
-- conditionally publish a result for the exact body revision it embedded, so an older slow job can
-- never overwrite a newer edit. `colorStatus` is pending | ready | failed.
ALTER TABLE post ADD COLUMN color TEXT;
ALTER TABLE post ADD COLUMN contentRevision TEXT NOT NULL DEFAULT '';
ALTER TABLE post ADD COLUMN colorRevision TEXT;
ALTER TABLE post ADD COLUMN colorProjectionVersion TEXT;
ALTER TABLE post ADD COLUMN colorStatus TEXT NOT NULL DEFAULT 'pending';

-- Array-shaped frontmatter is dual-written here while the existing JSON-string columns remain as a
-- compatibility read path. Link ids are deterministic hashes generated by the importer; every table
-- still has one primary key, as required by the Rindle change model.
CREATE TABLE postFacet (id TEXT NOT NULL, postId TEXT NOT NULL, facet TEXT NOT NULL, value TEXT NOT NULL, position REAL NOT NULL DEFAULT 0, PRIMARY KEY (id));
CREATE INDEX post_facet_by_post ON postFacet (postId, facet, position, id);
CREATE INDEX post_facet_by_value ON postFacet (facet, value, postId);

CREATE TABLE author (id TEXT NOT NULL, displayName TEXT NOT NULL, glyph TEXT, color TEXT, PRIMARY KEY (id));
CREATE TABLE postAuthor (id TEXT NOT NULL, postId TEXT NOT NULL, authorId TEXT NOT NULL, position REAL NOT NULL DEFAULT 0, PRIMARY KEY (id));
CREATE INDEX post_author_by_post ON postAuthor (postId, position, id);
CREATE INDEX post_author_by_author ON postAuthor (authorId, postId);
