/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WardrobeRouteImport } from './routes/wardrobe'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as OutfitsRouteImport } from './routes/outfits'
import { Route as NewRouteImport } from './routes/new'
import { Route as CompareRouteImport } from './routes/compare'
import { Route as BracketRouteImport } from './routes/bracket'
import { Route as IndexRouteImport } from './routes/index'
import { Route as OutfitsIdRouteImport } from './routes/outfits_.$id'
import { Route as ItemIdRouteImport } from './routes/item.$id'

const WardrobeRoute = WardrobeRouteImport.update({
  id: '/wardrobe',
  path: '/wardrobe',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const OutfitsRoute = OutfitsRouteImport.update({
  id: '/outfits',
  path: '/outfits',
  getParentRoute: () => rootRouteImport,
} as any)
const NewRoute = NewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => rootRouteImport,
} as any)
const CompareRoute = CompareRouteImport.update({
  id: '/compare',
  path: '/compare',
  getParentRoute: () => rootRouteImport,
} as any)
const BracketRoute = BracketRouteImport.update({
  id: '/bracket',
  path: '/bracket',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const OutfitsIdRoute = OutfitsIdRouteImport.update({
  id: '/outfits_/$id',
  path: '/outfits/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ItemIdRoute = ItemIdRouteImport.update({
  id: '/item/$id',
  path: '/item/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/bracket': typeof BracketRoute
  '/compare': typeof CompareRoute
  '/new': typeof NewRoute
  '/outfits': typeof OutfitsRoute
  '/settings': typeof SettingsRoute
  '/wardrobe': typeof WardrobeRoute
  '/item/$id': typeof ItemIdRoute
  '/outfits/$id': typeof OutfitsIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/bracket': typeof BracketRoute
  '/compare': typeof CompareRoute
  '/new': typeof NewRoute
  '/outfits': typeof OutfitsRoute
  '/settings': typeof SettingsRoute
  '/wardrobe': typeof WardrobeRoute
  '/item/$id': typeof ItemIdRoute
  '/outfits/$id': typeof OutfitsIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/bracket': typeof BracketRoute
  '/compare': typeof CompareRoute
  '/new': typeof NewRoute
  '/outfits': typeof OutfitsRoute
  '/settings': typeof SettingsRoute
  '/wardrobe': typeof WardrobeRoute
  '/item/$id': typeof ItemIdRoute
  '/outfits_/$id': typeof OutfitsIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/bracket'
    | '/compare'
    | '/new'
    | '/outfits'
    | '/settings'
    | '/wardrobe'
    | '/item/$id'
    | '/outfits/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/bracket'
    | '/compare'
    | '/new'
    | '/outfits'
    | '/settings'
    | '/wardrobe'
    | '/item/$id'
    | '/outfits/$id'
  id:
    | '__root__'
    | '/'
    | '/bracket'
    | '/compare'
    | '/new'
    | '/outfits'
    | '/settings'
    | '/wardrobe'
    | '/item/$id'
    | '/outfits_/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BracketRoute: typeof BracketRoute
  CompareRoute: typeof CompareRoute
  NewRoute: typeof NewRoute
  OutfitsRoute: typeof OutfitsRoute
  SettingsRoute: typeof SettingsRoute
  WardrobeRoute: typeof WardrobeRoute
  ItemIdRoute: typeof ItemIdRoute
  OutfitsIdRoute: typeof OutfitsIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/wardrobe': {
      id: '/wardrobe'
      path: '/wardrobe'
      fullPath: '/wardrobe'
      preLoaderRoute: typeof WardrobeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/outfits': {
      id: '/outfits'
      path: '/outfits'
      fullPath: '/outfits'
      preLoaderRoute: typeof OutfitsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/new': {
      id: '/new'
      path: '/new'
      fullPath: '/new'
      preLoaderRoute: typeof NewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compare': {
      id: '/compare'
      path: '/compare'
      fullPath: '/compare'
      preLoaderRoute: typeof CompareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bracket': {
      id: '/bracket'
      path: '/bracket'
      fullPath: '/bracket'
      preLoaderRoute: typeof BracketRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/outfits_/$id': {
      id: '/outfits_/$id'
      path: '/outfits/$id'
      fullPath: '/outfits/$id'
      preLoaderRoute: typeof OutfitsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/item/$id': {
      id: '/item/$id'
      path: '/item/$id'
      fullPath: '/item/$id'
      preLoaderRoute: typeof ItemIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BracketRoute: BracketRoute,
  CompareRoute: CompareRoute,
  NewRoute: NewRoute,
  OutfitsRoute: OutfitsRoute,
  SettingsRoute: SettingsRoute,
  WardrobeRoute: WardrobeRoute,
  ItemIdRoute: ItemIdRoute,
  OutfitsIdRoute: OutfitsIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
