/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ShellRouteImport } from './routes/_shell'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ThoughtsRouteImport } from './routes/thoughts'
import { Route as ShellIndexRouteImport } from './routes/_shell.index'
import { Route as ShellSlugRouteImport } from './routes/_shell.$slug'
import { Route as ShellWriteRouteImport } from './routes/_shell.write'
import { Route as ThoughtsIndexRouteImport } from './routes/thoughts.index'
import { Route as ThoughtsIdRouteImport } from './routes/thoughts.$id'
import { Route as ThoughtsBooksRouteImport } from './routes/thoughts.books'
import { Route as ThoughtsEventsRouteImport } from './routes/thoughts.events'
import { Route as ThoughtsLocationsRouteImport } from './routes/thoughts.locations'
import { Route as ThoughtsMoviesRouteImport } from './routes/thoughts.movies'
import { Route as ThoughtsMusicRouteImport } from './routes/thoughts.music'
import { Route as ThoughtsProjectsRouteImport } from './routes/thoughts.projects'
import { Route as ThoughtsQuestionsRouteImport } from './routes/thoughts.questions'
import { Route as ThoughtsTasksRouteImport } from './routes/thoughts.tasks'
import { Route as ApiAuthSplatRouteImport } from './routes/api.auth.$'
import { Route as ApiAuthDevLoginRouteImport } from './routes/api.auth.dev-login'
import { Route as ApiRindleMutateRouteImport } from './routes/api.rindle.mutate'
import { Route as ApiRindleQueryRouteImport } from './routes/api.rindle.query'
import { Route as ApiRindleReadRouteImport } from './routes/api.rindle.read'

const ShellRoute = ShellRouteImport.update({
  id: '/_shell',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ThoughtsRoute = ThoughtsRouteImport.update({
  id: '/thoughts',
  path: '/thoughts',
  getParentRoute: () => rootRouteImport,
} as any)
const ShellIndexRoute = ShellIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ShellRoute,
} as any)
const ShellSlugRoute = ShellSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => ShellRoute,
} as any)
const ShellWriteRoute = ShellWriteRouteImport.update({
  id: '/write',
  path: '/write',
  getParentRoute: () => ShellRoute,
} as any)
const ThoughtsIndexRoute = ThoughtsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ThoughtsRoute,
} as any)
const ThoughtsIdRoute = ThoughtsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ThoughtsRoute,
} as any)
const ThoughtsBooksRoute = ThoughtsBooksRouteImport.update({
  id: '/books',
  path: '/books',
  getParentRoute: () => ThoughtsRoute,
} as any)
const ThoughtsEventsRoute = ThoughtsEventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => ThoughtsRoute,
} as any)
const ThoughtsLocationsRoute = ThoughtsLocationsRouteImport.update({
  id: '/locations',
  path: '/locations',
  getParentRoute: () => ThoughtsRoute,
} as any)
const ThoughtsMoviesRoute = ThoughtsMoviesRouteImport.update({
  id: '/movies',
  path: '/movies',
  getParentRoute: () => ThoughtsRoute,
} as any)
const ThoughtsMusicRoute = ThoughtsMusicRouteImport.update({
  id: '/music',
  path: '/music',
  getParentRoute: () => ThoughtsRoute,
} as any)
const ThoughtsProjectsRoute = ThoughtsProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => ThoughtsRoute,
} as any)
const ThoughtsQuestionsRoute = ThoughtsQuestionsRouteImport.update({
  id: '/questions',
  path: '/questions',
  getParentRoute: () => ThoughtsRoute,
} as any)
const ThoughtsTasksRoute = ThoughtsTasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => ThoughtsRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthDevLoginRoute = ApiAuthDevLoginRouteImport.update({
  id: '/api/auth/dev-login',
  path: '/api/auth/dev-login',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRindleMutateRoute = ApiRindleMutateRouteImport.update({
  id: '/api/rindle/mutate',
  path: '/api/rindle/mutate',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRindleQueryRoute = ApiRindleQueryRouteImport.update({
  id: '/api/rindle/query',
  path: '/api/rindle/query',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRindleReadRoute = ApiRindleReadRouteImport.update({
  id: '/api/rindle/read',
  path: '/api/rindle/read',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof ShellIndexRoute
  '/login': typeof LoginRoute
  '/thoughts': typeof ThoughtsRouteWithChildren
  '/$slug': typeof ShellSlugRoute
  '/write': typeof ShellWriteRoute
  '/thoughts/$id': typeof ThoughtsIdRoute
  '/thoughts/books': typeof ThoughtsBooksRoute
  '/thoughts/events': typeof ThoughtsEventsRoute
  '/thoughts/locations': typeof ThoughtsLocationsRoute
  '/thoughts/movies': typeof ThoughtsMoviesRoute
  '/thoughts/music': typeof ThoughtsMusicRoute
  '/thoughts/projects': typeof ThoughtsProjectsRoute
  '/thoughts/questions': typeof ThoughtsQuestionsRoute
  '/thoughts/tasks': typeof ThoughtsTasksRoute
  '/thoughts/': typeof ThoughtsIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/auth/dev-login': typeof ApiAuthDevLoginRoute
  '/api/rindle/mutate': typeof ApiRindleMutateRoute
  '/api/rindle/query': typeof ApiRindleQueryRoute
  '/api/rindle/read': typeof ApiRindleReadRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/$slug': typeof ShellSlugRoute
  '/write': typeof ShellWriteRoute
  '/thoughts/$id': typeof ThoughtsIdRoute
  '/thoughts/books': typeof ThoughtsBooksRoute
  '/thoughts/events': typeof ThoughtsEventsRoute
  '/thoughts/locations': typeof ThoughtsLocationsRoute
  '/thoughts/movies': typeof ThoughtsMoviesRoute
  '/thoughts/music': typeof ThoughtsMusicRoute
  '/thoughts/projects': typeof ThoughtsProjectsRoute
  '/thoughts/questions': typeof ThoughtsQuestionsRoute
  '/thoughts/tasks': typeof ThoughtsTasksRoute
  '/': typeof ShellIndexRoute
  '/thoughts': typeof ThoughtsIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/auth/dev-login': typeof ApiAuthDevLoginRoute
  '/api/rindle/mutate': typeof ApiRindleMutateRoute
  '/api/rindle/query': typeof ApiRindleQueryRoute
  '/api/rindle/read': typeof ApiRindleReadRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_shell': typeof ShellRouteWithChildren
  '/login': typeof LoginRoute
  '/thoughts': typeof ThoughtsRouteWithChildren
  '/_shell/$slug': typeof ShellSlugRoute
  '/_shell/write': typeof ShellWriteRoute
  '/thoughts/$id': typeof ThoughtsIdRoute
  '/thoughts/books': typeof ThoughtsBooksRoute
  '/thoughts/events': typeof ThoughtsEventsRoute
  '/thoughts/locations': typeof ThoughtsLocationsRoute
  '/thoughts/movies': typeof ThoughtsMoviesRoute
  '/thoughts/music': typeof ThoughtsMusicRoute
  '/thoughts/projects': typeof ThoughtsProjectsRoute
  '/thoughts/questions': typeof ThoughtsQuestionsRoute
  '/thoughts/tasks': typeof ThoughtsTasksRoute
  '/_shell/': typeof ShellIndexRoute
  '/thoughts/': typeof ThoughtsIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/auth/dev-login': typeof ApiAuthDevLoginRoute
  '/api/rindle/mutate': typeof ApiRindleMutateRoute
  '/api/rindle/query': typeof ApiRindleQueryRoute
  '/api/rindle/read': typeof ApiRindleReadRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/thoughts'
    | '/$slug'
    | '/write'
    | '/thoughts/$id'
    | '/thoughts/books'
    | '/thoughts/events'
    | '/thoughts/locations'
    | '/thoughts/movies'
    | '/thoughts/music'
    | '/thoughts/projects'
    | '/thoughts/questions'
    | '/thoughts/tasks'
    | '/thoughts/'
    | '/api/auth/$'
    | '/api/auth/dev-login'
    | '/api/rindle/mutate'
    | '/api/rindle/query'
    | '/api/rindle/read'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/$slug'
    | '/write'
    | '/thoughts/$id'
    | '/thoughts/books'
    | '/thoughts/events'
    | '/thoughts/locations'
    | '/thoughts/movies'
    | '/thoughts/music'
    | '/thoughts/projects'
    | '/thoughts/questions'
    | '/thoughts/tasks'
    | '/'
    | '/thoughts'
    | '/api/auth/$'
    | '/api/auth/dev-login'
    | '/api/rindle/mutate'
    | '/api/rindle/query'
    | '/api/rindle/read'
  id:
    | '__root__'
    | '/_shell'
    | '/login'
    | '/thoughts'
    | '/_shell/$slug'
    | '/_shell/write'
    | '/thoughts/$id'
    | '/thoughts/books'
    | '/thoughts/events'
    | '/thoughts/locations'
    | '/thoughts/movies'
    | '/thoughts/music'
    | '/thoughts/projects'
    | '/thoughts/questions'
    | '/thoughts/tasks'
    | '/_shell/'
    | '/thoughts/'
    | '/api/auth/$'
    | '/api/auth/dev-login'
    | '/api/rindle/mutate'
    | '/api/rindle/query'
    | '/api/rindle/read'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  ShellRoute: typeof ShellRouteWithChildren
  LoginRoute: typeof LoginRoute
  ThoughtsRoute: typeof ThoughtsRouteWithChildren
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiAuthDevLoginRoute: typeof ApiAuthDevLoginRoute
  ApiRindleMutateRoute: typeof ApiRindleMutateRoute
  ApiRindleQueryRoute: typeof ApiRindleQueryRoute
  ApiRindleReadRoute: typeof ApiRindleReadRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_shell': {
      id: '/_shell'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ShellRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/thoughts': {
      id: '/thoughts'
      path: '/thoughts'
      fullPath: '/thoughts'
      preLoaderRoute: typeof ThoughtsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_shell/': {
      id: '/_shell/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof ShellIndexRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/$slug': {
      id: '/_shell/$slug'
      path: '/$slug'
      fullPath: '/$slug'
      preLoaderRoute: typeof ShellSlugRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/write': {
      id: '/_shell/write'
      path: '/write'
      fullPath: '/write'
      preLoaderRoute: typeof ShellWriteRouteImport
      parentRoute: typeof ShellRoute
    }
    '/thoughts/': {
      id: '/thoughts/'
      path: '/'
      fullPath: '/thoughts/'
      preLoaderRoute: typeof ThoughtsIndexRouteImport
      parentRoute: typeof ThoughtsRoute
    }
    '/thoughts/$id': {
      id: '/thoughts/$id'
      path: '/$id'
      fullPath: '/thoughts/$id'
      preLoaderRoute: typeof ThoughtsIdRouteImport
      parentRoute: typeof ThoughtsRoute
    }
    '/thoughts/books': {
      id: '/thoughts/books'
      path: '/books'
      fullPath: '/thoughts/books'
      preLoaderRoute: typeof ThoughtsBooksRouteImport
      parentRoute: typeof ThoughtsRoute
    }
    '/thoughts/events': {
      id: '/thoughts/events'
      path: '/events'
      fullPath: '/thoughts/events'
      preLoaderRoute: typeof ThoughtsEventsRouteImport
      parentRoute: typeof ThoughtsRoute
    }
    '/thoughts/locations': {
      id: '/thoughts/locations'
      path: '/locations'
      fullPath: '/thoughts/locations'
      preLoaderRoute: typeof ThoughtsLocationsRouteImport
      parentRoute: typeof ThoughtsRoute
    }
    '/thoughts/movies': {
      id: '/thoughts/movies'
      path: '/movies'
      fullPath: '/thoughts/movies'
      preLoaderRoute: typeof ThoughtsMoviesRouteImport
      parentRoute: typeof ThoughtsRoute
    }
    '/thoughts/music': {
      id: '/thoughts/music'
      path: '/music'
      fullPath: '/thoughts/music'
      preLoaderRoute: typeof ThoughtsMusicRouteImport
      parentRoute: typeof ThoughtsRoute
    }
    '/thoughts/projects': {
      id: '/thoughts/projects'
      path: '/projects'
      fullPath: '/thoughts/projects'
      preLoaderRoute: typeof ThoughtsProjectsRouteImport
      parentRoute: typeof ThoughtsRoute
    }
    '/thoughts/questions': {
      id: '/thoughts/questions'
      path: '/questions'
      fullPath: '/thoughts/questions'
      preLoaderRoute: typeof ThoughtsQuestionsRouteImport
      parentRoute: typeof ThoughtsRoute
    }
    '/thoughts/tasks': {
      id: '/thoughts/tasks'
      path: '/tasks'
      fullPath: '/thoughts/tasks'
      preLoaderRoute: typeof ThoughtsTasksRouteImport
      parentRoute: typeof ThoughtsRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/dev-login': {
      id: '/api/auth/dev-login'
      path: '/api/auth/dev-login'
      fullPath: '/api/auth/dev-login'
      preLoaderRoute: typeof ApiAuthDevLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/rindle/mutate': {
      id: '/api/rindle/mutate'
      path: '/api/rindle/mutate'
      fullPath: '/api/rindle/mutate'
      preLoaderRoute: typeof ApiRindleMutateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/rindle/query': {
      id: '/api/rindle/query'
      path: '/api/rindle/query'
      fullPath: '/api/rindle/query'
      preLoaderRoute: typeof ApiRindleQueryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/rindle/read': {
      id: '/api/rindle/read'
      path: '/api/rindle/read'
      fullPath: '/api/rindle/read'
      preLoaderRoute: typeof ApiRindleReadRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface ShellRouteChildren {
  ShellSlugRoute: typeof ShellSlugRoute
  ShellWriteRoute: typeof ShellWriteRoute
  ShellIndexRoute: typeof ShellIndexRoute
}

const ShellRouteChildren: ShellRouteChildren = {
  ShellSlugRoute: ShellSlugRoute,
  ShellWriteRoute: ShellWriteRoute,
  ShellIndexRoute: ShellIndexRoute,
}

const ShellRouteWithChildren = ShellRoute._addFileChildren(ShellRouteChildren)

interface ThoughtsRouteChildren {
  ThoughtsIdRoute: typeof ThoughtsIdRoute
  ThoughtsBooksRoute: typeof ThoughtsBooksRoute
  ThoughtsEventsRoute: typeof ThoughtsEventsRoute
  ThoughtsLocationsRoute: typeof ThoughtsLocationsRoute
  ThoughtsMoviesRoute: typeof ThoughtsMoviesRoute
  ThoughtsMusicRoute: typeof ThoughtsMusicRoute
  ThoughtsProjectsRoute: typeof ThoughtsProjectsRoute
  ThoughtsQuestionsRoute: typeof ThoughtsQuestionsRoute
  ThoughtsTasksRoute: typeof ThoughtsTasksRoute
  ThoughtsIndexRoute: typeof ThoughtsIndexRoute
}

const ThoughtsRouteChildren: ThoughtsRouteChildren = {
  ThoughtsIdRoute: ThoughtsIdRoute,
  ThoughtsBooksRoute: ThoughtsBooksRoute,
  ThoughtsEventsRoute: ThoughtsEventsRoute,
  ThoughtsLocationsRoute: ThoughtsLocationsRoute,
  ThoughtsMoviesRoute: ThoughtsMoviesRoute,
  ThoughtsMusicRoute: ThoughtsMusicRoute,
  ThoughtsProjectsRoute: ThoughtsProjectsRoute,
  ThoughtsQuestionsRoute: ThoughtsQuestionsRoute,
  ThoughtsTasksRoute: ThoughtsTasksRoute,
  ThoughtsIndexRoute: ThoughtsIndexRoute,
}

const ThoughtsRouteWithChildren = ThoughtsRoute._addFileChildren(
  ThoughtsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  ShellRoute: ShellRouteWithChildren,
  LoginRoute: LoginRoute,
  ThoughtsRoute: ThoughtsRouteWithChildren,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiAuthDevLoginRoute: ApiAuthDevLoginRoute,
  ApiRindleMutateRoute: ApiRindleMutateRoute,
  ApiRindleQueryRoute: ApiRindleQueryRoute,
  ApiRindleReadRoute: ApiRindleReadRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
