/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ShellRouteImport } from './routes/_shell'
import { Route as ExploreRouteImport } from './routes/explore'
import { Route as LoginRouteImport } from './routes/login'
import { Route as PasteRouteImport } from './routes/paste'
import { Route as SearchRouteImport } from './routes/search'
import { Route as ThoughtsRouteImport } from './routes/thoughts'
import { Route as ShellIndexRouteImport } from './routes/_shell.index'
import { Route as ShellSlugRouteImport } from './routes/_shell.$slug'
import { Route as ShellWriteRouteImport } from './routes/_shell.write'
import { Route as PasteIndexRouteImport } from './routes/paste.index'
import { Route as PasteIdRouteImport } from './routes/paste.$id'
import { Route as PasteAllRouteImport } from './routes/paste.all'
import { Route as ThoughtsIndexRouteImport } from './routes/thoughts.index'
import { Route as ThoughtsIdRouteImport } from './routes/thoughts.$id'
import { Route as ThoughtsBooksRouteImport } from './routes/thoughts.books'
import { Route as ThoughtsEventsRouteImport } from './routes/thoughts.events'
import { Route as ThoughtsLocationsRouteImport } from './routes/thoughts.locations'
import { Route as ThoughtsMoviesRouteImport } from './routes/thoughts.movies'
import { Route as ThoughtsMusicRouteImport } from './routes/thoughts.music'
import { Route as ThoughtsProjectsRouteImport } from './routes/thoughts.projects'
import { Route as ThoughtsQuestionsRouteImport } from './routes/thoughts.questions'
import { Route as ThoughtsTasksRouteImport } from './routes/thoughts.tasks'
import { Route as ApiAttachmentsSplatRouteImport } from './routes/api.attachments.$'
import { Route as ApiAuthSplatRouteImport } from './routes/api.auth.$'
import { Route as ApiAuthDevLoginRouteImport } from './routes/api.auth.dev-login'
import { Route as ApiRindleMutateRouteImport } from './routes/api.rindle.mutate'
import { Route as ApiRindleQueryRouteImport } from './routes/api.rindle.query'
import { Route as ApiRindleReadRouteImport } from './routes/api.rindle.read'
import { Route as PasteIdIndexRouteImport } from './routes/paste.$id.index'
import { Route as PasteIdDiffRouteImport } from './routes/paste.$id.diff'
import { Route as PasteIdModuleRouteImport } from './routes/paste.$id.module'
import { Route as PasteIdRawRouteImport } from './routes/paste.$id.raw'
import { Route as PasteForkIdRouteImport } from './routes/paste.fork.$id'
import { Route as ThoughtsFramingsIndexRouteImport } from './routes/thoughts.framings.index'
import { Route as ThoughtsFramingsIdRouteImport } from './routes/thoughts.framings.$id'
import { Route as ThoughtsTIdRouteImport } from './routes/thoughts.t.$id'

const ShellRoute = ShellRouteImport.update({
  id: '/_shell',
  getParentRoute: () => rootRouteImport,
} as any)
const ExploreRoute = ExploreRouteImport.update({
  id: '/explore',
  path: '/explore',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const PasteRoute = PasteRouteImport.update({
  id: '/paste',
  path: '/paste',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const ThoughtsRoute = ThoughtsRouteImport.update({
  id: '/thoughts',
  path: '/thoughts',
  getParentRoute: () => rootRouteImport,
} as any)
const ShellIndexRoute = ShellIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ShellRoute,
} as any)
const ShellSlugRoute = ShellSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => ShellRoute,
} as any)
const ShellWriteRoute = ShellWriteRouteImport.update({
  id: '/write',
  path: '/write',
  getParentRoute: () => ShellRoute,
} as any)
const PasteIndexRoute = PasteIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PasteRoute,
} as any)
const PasteIdRoute = PasteIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => PasteRoute,
} as any)
const PasteAllRoute = PasteAllRouteImport.update({
  id: '/all',
  path: '/all',
  getParentRoute: () => PasteRoute,
} as any)
const ThoughtsIndexRoute = ThoughtsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ThoughtsRoute,
} as any)
const ThoughtsIdRoute = ThoughtsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ThoughtsRoute,
} as any)
const ThoughtsBooksRoute = ThoughtsBooksRouteImport.update({
  id: '/books',
  path: '/books',
  getParentRoute: () => ThoughtsRoute,
} as any)
const ThoughtsEventsRoute = ThoughtsEventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => ThoughtsRoute,
} as any)
const ThoughtsLocationsRoute = ThoughtsLocationsRouteImport.update({
  id: '/locations',
  path: '/locations',
  getParentRoute: () => ThoughtsRoute,
} as any)
const ThoughtsMoviesRoute = ThoughtsMoviesRouteImport.update({
  id: '/movies',
  path: '/movies',
  getParentRoute: () => ThoughtsRoute,
} as any)
const ThoughtsMusicRoute = ThoughtsMusicRouteImport.update({
  id: '/music',
  path: '/music',
  getParentRoute: () => ThoughtsRoute,
} as any)
const ThoughtsProjectsRoute = ThoughtsProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => ThoughtsRoute,
} as any)
const ThoughtsQuestionsRoute = ThoughtsQuestionsRouteImport.update({
  id: '/questions',
  path: '/questions',
  getParentRoute: () => ThoughtsRoute,
} as any)
const ThoughtsTasksRoute = ThoughtsTasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => ThoughtsRoute,
} as any)
const ApiAttachmentsSplatRoute = ApiAttachmentsSplatRouteImport.update({
  id: '/api/attachments/$',
  path: '/api/attachments/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthDevLoginRoute = ApiAuthDevLoginRouteImport.update({
  id: '/api/auth/dev-login',
  path: '/api/auth/dev-login',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRindleMutateRoute = ApiRindleMutateRouteImport.update({
  id: '/api/rindle/mutate',
  path: '/api/rindle/mutate',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRindleQueryRoute = ApiRindleQueryRouteImport.update({
  id: '/api/rindle/query',
  path: '/api/rindle/query',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRindleReadRoute = ApiRindleReadRouteImport.update({
  id: '/api/rindle/read',
  path: '/api/rindle/read',
  getParentRoute: () => rootRouteImport,
} as any)
const PasteIdIndexRoute = PasteIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PasteIdRoute,
} as any)
const PasteIdDiffRoute = PasteIdDiffRouteImport.update({
  id: '/diff',
  path: '/diff',
  getParentRoute: () => PasteIdRoute,
} as any)
const PasteIdModuleRoute = PasteIdModuleRouteImport.update({
  id: '/module',
  path: '/module',
  getParentRoute: () => PasteIdRoute,
} as any)
const PasteIdRawRoute = PasteIdRawRouteImport.update({
  id: '/raw',
  path: '/raw',
  getParentRoute: () => PasteIdRoute,
} as any)
const PasteForkIdRoute = PasteForkIdRouteImport.update({
  id: '/fork/$id',
  path: '/fork/$id',
  getParentRoute: () => PasteRoute,
} as any)
const ThoughtsFramingsIndexRoute = ThoughtsFramingsIndexRouteImport.update({
  id: '/framings/',
  path: '/framings/',
  getParentRoute: () => ThoughtsRoute,
} as any)
const ThoughtsFramingsIdRoute = ThoughtsFramingsIdRouteImport.update({
  id: '/framings/$id',
  path: '/framings/$id',
  getParentRoute: () => ThoughtsRoute,
} as any)
const ThoughtsTIdRoute = ThoughtsTIdRouteImport.update({
  id: '/t/$id',
  path: '/t/$id',
  getParentRoute: () => ThoughtsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof ShellIndexRoute
  '/explore': typeof ExploreRoute
  '/login': typeof LoginRoute
  '/paste': typeof PasteRouteWithChildren
  '/search': typeof SearchRoute
  '/thoughts': typeof ThoughtsRouteWithChildren
  '/$slug': typeof ShellSlugRoute
  '/write': typeof ShellWriteRoute
  '/paste/$id': typeof PasteIdRouteWithChildren
  '/paste/all': typeof PasteAllRoute
  '/thoughts/$id': typeof ThoughtsIdRoute
  '/thoughts/books': typeof ThoughtsBooksRoute
  '/thoughts/events': typeof ThoughtsEventsRoute
  '/thoughts/locations': typeof ThoughtsLocationsRoute
  '/thoughts/movies': typeof ThoughtsMoviesRoute
  '/thoughts/music': typeof ThoughtsMusicRoute
  '/thoughts/projects': typeof ThoughtsProjectsRoute
  '/thoughts/questions': typeof ThoughtsQuestionsRoute
  '/thoughts/tasks': typeof ThoughtsTasksRoute
  '/paste/': typeof PasteIndexRoute
  '/thoughts/': typeof ThoughtsIndexRoute
  '/api/attachments/$': typeof ApiAttachmentsSplatRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/auth/dev-login': typeof ApiAuthDevLoginRoute
  '/api/rindle/mutate': typeof ApiRindleMutateRoute
  '/api/rindle/query': typeof ApiRindleQueryRoute
  '/api/rindle/read': typeof ApiRindleReadRoute
  '/paste/$id/diff': typeof PasteIdDiffRoute
  '/paste/$id/module': typeof PasteIdModuleRoute
  '/paste/$id/raw': typeof PasteIdRawRoute
  '/paste/fork/$id': typeof PasteForkIdRoute
  '/thoughts/framings/$id': typeof ThoughtsFramingsIdRoute
  '/thoughts/t/$id': typeof ThoughtsTIdRoute
  '/paste/$id/': typeof PasteIdIndexRoute
  '/thoughts/framings/': typeof ThoughtsFramingsIndexRoute
}
export interface FileRoutesByTo {
  '/explore': typeof ExploreRoute
  '/login': typeof LoginRoute
  '/search': typeof SearchRoute
  '/$slug': typeof ShellSlugRoute
  '/write': typeof ShellWriteRoute
  '/paste/all': typeof PasteAllRoute
  '/thoughts/$id': typeof ThoughtsIdRoute
  '/thoughts/books': typeof ThoughtsBooksRoute
  '/thoughts/events': typeof ThoughtsEventsRoute
  '/thoughts/locations': typeof ThoughtsLocationsRoute
  '/thoughts/movies': typeof ThoughtsMoviesRoute
  '/thoughts/music': typeof ThoughtsMusicRoute
  '/thoughts/projects': typeof ThoughtsProjectsRoute
  '/thoughts/questions': typeof ThoughtsQuestionsRoute
  '/thoughts/tasks': typeof ThoughtsTasksRoute
  '/': typeof ShellIndexRoute
  '/paste': typeof PasteIndexRoute
  '/thoughts': typeof ThoughtsIndexRoute
  '/api/attachments/$': typeof ApiAttachmentsSplatRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/auth/dev-login': typeof ApiAuthDevLoginRoute
  '/api/rindle/mutate': typeof ApiRindleMutateRoute
  '/api/rindle/query': typeof ApiRindleQueryRoute
  '/api/rindle/read': typeof ApiRindleReadRoute
  '/paste/$id/diff': typeof PasteIdDiffRoute
  '/paste/$id/module': typeof PasteIdModuleRoute
  '/paste/$id/raw': typeof PasteIdRawRoute
  '/paste/fork/$id': typeof PasteForkIdRoute
  '/thoughts/framings/$id': typeof ThoughtsFramingsIdRoute
  '/thoughts/t/$id': typeof ThoughtsTIdRoute
  '/paste/$id': typeof PasteIdIndexRoute
  '/thoughts/framings': typeof ThoughtsFramingsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_shell': typeof ShellRouteWithChildren
  '/explore': typeof ExploreRoute
  '/login': typeof LoginRoute
  '/paste': typeof PasteRouteWithChildren
  '/search': typeof SearchRoute
  '/thoughts': typeof ThoughtsRouteWithChildren
  '/_shell/$slug': typeof ShellSlugRoute
  '/_shell/write': typeof ShellWriteRoute
  '/paste/$id': typeof PasteIdRouteWithChildren
  '/paste/all': typeof PasteAllRoute
  '/thoughts/$id': typeof ThoughtsIdRoute
  '/thoughts/books': typeof ThoughtsBooksRoute
  '/thoughts/events': typeof ThoughtsEventsRoute
  '/thoughts/locations': typeof ThoughtsLocationsRoute
  '/thoughts/movies': typeof ThoughtsMoviesRoute
  '/thoughts/music': typeof ThoughtsMusicRoute
  '/thoughts/projects': typeof ThoughtsProjectsRoute
  '/thoughts/questions': typeof ThoughtsQuestionsRoute
  '/thoughts/tasks': typeof ThoughtsTasksRoute
  '/_shell/': typeof ShellIndexRoute
  '/paste/': typeof PasteIndexRoute
  '/thoughts/': typeof ThoughtsIndexRoute
  '/api/attachments/$': typeof ApiAttachmentsSplatRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/auth/dev-login': typeof ApiAuthDevLoginRoute
  '/api/rindle/mutate': typeof ApiRindleMutateRoute
  '/api/rindle/query': typeof ApiRindleQueryRoute
  '/api/rindle/read': typeof ApiRindleReadRoute
  '/paste/$id/diff': typeof PasteIdDiffRoute
  '/paste/$id/module': typeof PasteIdModuleRoute
  '/paste/$id/raw': typeof PasteIdRawRoute
  '/paste/fork/$id': typeof PasteForkIdRoute
  '/thoughts/framings/$id': typeof ThoughtsFramingsIdRoute
  '/thoughts/t/$id': typeof ThoughtsTIdRoute
  '/paste/$id/': typeof PasteIdIndexRoute
  '/thoughts/framings/': typeof ThoughtsFramingsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/explore'
    | '/login'
    | '/paste'
    | '/search'
    | '/thoughts'
    | '/$slug'
    | '/write'
    | '/paste/$id'
    | '/paste/all'
    | '/thoughts/$id'
    | '/thoughts/books'
    | '/thoughts/events'
    | '/thoughts/locations'
    | '/thoughts/movies'
    | '/thoughts/music'
    | '/thoughts/projects'
    | '/thoughts/questions'
    | '/thoughts/tasks'
    | '/paste/'
    | '/thoughts/'
    | '/api/attachments/$'
    | '/api/auth/$'
    | '/api/auth/dev-login'
    | '/api/rindle/mutate'
    | '/api/rindle/query'
    | '/api/rindle/read'
    | '/paste/$id/diff'
    | '/paste/$id/module'
    | '/paste/$id/raw'
    | '/paste/fork/$id'
    | '/thoughts/framings/$id'
    | '/thoughts/t/$id'
    | '/paste/$id/'
    | '/thoughts/framings/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/explore'
    | '/login'
    | '/search'
    | '/$slug'
    | '/write'
    | '/paste/all'
    | '/thoughts/$id'
    | '/thoughts/books'
    | '/thoughts/events'
    | '/thoughts/locations'
    | '/thoughts/movies'
    | '/thoughts/music'
    | '/thoughts/projects'
    | '/thoughts/questions'
    | '/thoughts/tasks'
    | '/'
    | '/paste'
    | '/thoughts'
    | '/api/attachments/$'
    | '/api/auth/$'
    | '/api/auth/dev-login'
    | '/api/rindle/mutate'
    | '/api/rindle/query'
    | '/api/rindle/read'
    | '/paste/$id/diff'
    | '/paste/$id/module'
    | '/paste/$id/raw'
    | '/paste/fork/$id'
    | '/thoughts/framings/$id'
    | '/thoughts/t/$id'
    | '/paste/$id'
    | '/thoughts/framings'
  id:
    | '__root__'
    | '/_shell'
    | '/explore'
    | '/login'
    | '/paste'
    | '/search'
    | '/thoughts'
    | '/_shell/$slug'
    | '/_shell/write'
    | '/paste/$id'
    | '/paste/all'
    | '/thoughts/$id'
    | '/thoughts/books'
    | '/thoughts/events'
    | '/thoughts/locations'
    | '/thoughts/movies'
    | '/thoughts/music'
    | '/thoughts/projects'
    | '/thoughts/questions'
    | '/thoughts/tasks'
    | '/_shell/'
    | '/paste/'
    | '/thoughts/'
    | '/api/attachments/$'
    | '/api/auth/$'
    | '/api/auth/dev-login'
    | '/api/rindle/mutate'
    | '/api/rindle/query'
    | '/api/rindle/read'
    | '/paste/$id/diff'
    | '/paste/$id/module'
    | '/paste/$id/raw'
    | '/paste/fork/$id'
    | '/thoughts/framings/$id'
    | '/thoughts/t/$id'
    | '/paste/$id/'
    | '/thoughts/framings/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  ShellRoute: typeof ShellRouteWithChildren
  ExploreRoute: typeof ExploreRoute
  LoginRoute: typeof LoginRoute
  PasteRoute: typeof PasteRouteWithChildren
  SearchRoute: typeof SearchRoute
  ThoughtsRoute: typeof ThoughtsRouteWithChildren
  ApiAttachmentsSplatRoute: typeof ApiAttachmentsSplatRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiAuthDevLoginRoute: typeof ApiAuthDevLoginRoute
  ApiRindleMutateRoute: typeof ApiRindleMutateRoute
  ApiRindleQueryRoute: typeof ApiRindleQueryRoute
  ApiRindleReadRoute: typeof ApiRindleReadRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_shell': {
      id: '/_shell'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ShellRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explore': {
      id: '/explore'
      path: '/explore'
      fullPath: '/explore'
      preLoaderRoute: typeof ExploreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/paste': {
      id: '/paste'
      path: '/paste'
      fullPath: '/paste'
      preLoaderRoute: typeof PasteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/thoughts': {
      id: '/thoughts'
      path: '/thoughts'
      fullPath: '/thoughts'
      preLoaderRoute: typeof ThoughtsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_shell/': {
      id: '/_shell/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof ShellIndexRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/$slug': {
      id: '/_shell/$slug'
      path: '/$slug'
      fullPath: '/$slug'
      preLoaderRoute: typeof ShellSlugRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/write': {
      id: '/_shell/write'
      path: '/write'
      fullPath: '/write'
      preLoaderRoute: typeof ShellWriteRouteImport
      parentRoute: typeof ShellRoute
    }
    '/paste/': {
      id: '/paste/'
      path: '/'
      fullPath: '/paste/'
      preLoaderRoute: typeof PasteIndexRouteImport
      parentRoute: typeof PasteRoute
    }
    '/paste/$id': {
      id: '/paste/$id'
      path: '/$id'
      fullPath: '/paste/$id'
      preLoaderRoute: typeof PasteIdRouteImport
      parentRoute: typeof PasteRoute
    }
    '/paste/all': {
      id: '/paste/all'
      path: '/all'
      fullPath: '/paste/all'
      preLoaderRoute: typeof PasteAllRouteImport
      parentRoute: typeof PasteRoute
    }
    '/thoughts/': {
      id: '/thoughts/'
      path: '/'
      fullPath: '/thoughts/'
      preLoaderRoute: typeof ThoughtsIndexRouteImport
      parentRoute: typeof ThoughtsRoute
    }
    '/thoughts/$id': {
      id: '/thoughts/$id'
      path: '/$id'
      fullPath: '/thoughts/$id'
      preLoaderRoute: typeof ThoughtsIdRouteImport
      parentRoute: typeof ThoughtsRoute
    }
    '/thoughts/books': {
      id: '/thoughts/books'
      path: '/books'
      fullPath: '/thoughts/books'
      preLoaderRoute: typeof ThoughtsBooksRouteImport
      parentRoute: typeof ThoughtsRoute
    }
    '/thoughts/events': {
      id: '/thoughts/events'
      path: '/events'
      fullPath: '/thoughts/events'
      preLoaderRoute: typeof ThoughtsEventsRouteImport
      parentRoute: typeof ThoughtsRoute
    }
    '/thoughts/locations': {
      id: '/thoughts/locations'
      path: '/locations'
      fullPath: '/thoughts/locations'
      preLoaderRoute: typeof ThoughtsLocationsRouteImport
      parentRoute: typeof ThoughtsRoute
    }
    '/thoughts/movies': {
      id: '/thoughts/movies'
      path: '/movies'
      fullPath: '/thoughts/movies'
      preLoaderRoute: typeof ThoughtsMoviesRouteImport
      parentRoute: typeof ThoughtsRoute
    }
    '/thoughts/music': {
      id: '/thoughts/music'
      path: '/music'
      fullPath: '/thoughts/music'
      preLoaderRoute: typeof ThoughtsMusicRouteImport
      parentRoute: typeof ThoughtsRoute
    }
    '/thoughts/projects': {
      id: '/thoughts/projects'
      path: '/projects'
      fullPath: '/thoughts/projects'
      preLoaderRoute: typeof ThoughtsProjectsRouteImport
      parentRoute: typeof ThoughtsRoute
    }
    '/thoughts/questions': {
      id: '/thoughts/questions'
      path: '/questions'
      fullPath: '/thoughts/questions'
      preLoaderRoute: typeof ThoughtsQuestionsRouteImport
      parentRoute: typeof ThoughtsRoute
    }
    '/thoughts/tasks': {
      id: '/thoughts/tasks'
      path: '/tasks'
      fullPath: '/thoughts/tasks'
      preLoaderRoute: typeof ThoughtsTasksRouteImport
      parentRoute: typeof ThoughtsRoute
    }
    '/api/attachments/$': {
      id: '/api/attachments/$'
      path: '/api/attachments/$'
      fullPath: '/api/attachments/$'
      preLoaderRoute: typeof ApiAttachmentsSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/dev-login': {
      id: '/api/auth/dev-login'
      path: '/api/auth/dev-login'
      fullPath: '/api/auth/dev-login'
      preLoaderRoute: typeof ApiAuthDevLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/rindle/mutate': {
      id: '/api/rindle/mutate'
      path: '/api/rindle/mutate'
      fullPath: '/api/rindle/mutate'
      preLoaderRoute: typeof ApiRindleMutateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/rindle/query': {
      id: '/api/rindle/query'
      path: '/api/rindle/query'
      fullPath: '/api/rindle/query'
      preLoaderRoute: typeof ApiRindleQueryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/rindle/read': {
      id: '/api/rindle/read'
      path: '/api/rindle/read'
      fullPath: '/api/rindle/read'
      preLoaderRoute: typeof ApiRindleReadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/paste/$id/': {
      id: '/paste/$id/'
      path: '/'
      fullPath: '/paste/$id/'
      preLoaderRoute: typeof PasteIdIndexRouteImport
      parentRoute: typeof PasteIdRoute
    }
    '/paste/$id/diff': {
      id: '/paste/$id/diff'
      path: '/diff'
      fullPath: '/paste/$id/diff'
      preLoaderRoute: typeof PasteIdDiffRouteImport
      parentRoute: typeof PasteIdRoute
    }
    '/paste/$id/module': {
      id: '/paste/$id/module'
      path: '/module'
      fullPath: '/paste/$id/module'
      preLoaderRoute: typeof PasteIdModuleRouteImport
      parentRoute: typeof PasteIdRoute
    }
    '/paste/$id/raw': {
      id: '/paste/$id/raw'
      path: '/raw'
      fullPath: '/paste/$id/raw'
      preLoaderRoute: typeof PasteIdRawRouteImport
      parentRoute: typeof PasteIdRoute
    }
    '/paste/fork/$id': {
      id: '/paste/fork/$id'
      path: '/fork/$id'
      fullPath: '/paste/fork/$id'
      preLoaderRoute: typeof PasteForkIdRouteImport
      parentRoute: typeof PasteRoute
    }
    '/thoughts/framings/': {
      id: '/thoughts/framings/'
      path: '/framings'
      fullPath: '/thoughts/framings/'
      preLoaderRoute: typeof ThoughtsFramingsIndexRouteImport
      parentRoute: typeof ThoughtsRoute
    }
    '/thoughts/framings/$id': {
      id: '/thoughts/framings/$id'
      path: '/framings/$id'
      fullPath: '/thoughts/framings/$id'
      preLoaderRoute: typeof ThoughtsFramingsIdRouteImport
      parentRoute: typeof ThoughtsRoute
    }
    '/thoughts/t/$id': {
      id: '/thoughts/t/$id'
      path: '/t/$id'
      fullPath: '/thoughts/t/$id'
      preLoaderRoute: typeof ThoughtsTIdRouteImport
      parentRoute: typeof ThoughtsRoute
    }
  }
}

interface ShellRouteChildren {
  ShellSlugRoute: typeof ShellSlugRoute
  ShellWriteRoute: typeof ShellWriteRoute
  ShellIndexRoute: typeof ShellIndexRoute
}

const ShellRouteChildren: ShellRouteChildren = {
  ShellSlugRoute: ShellSlugRoute,
  ShellWriteRoute: ShellWriteRoute,
  ShellIndexRoute: ShellIndexRoute,
}

const ShellRouteWithChildren = ShellRoute._addFileChildren(ShellRouteChildren)

interface PasteIdRouteChildren {
  PasteIdDiffRoute: typeof PasteIdDiffRoute
  PasteIdModuleRoute: typeof PasteIdModuleRoute
  PasteIdRawRoute: typeof PasteIdRawRoute
  PasteIdIndexRoute: typeof PasteIdIndexRoute
}

const PasteIdRouteChildren: PasteIdRouteChildren = {
  PasteIdDiffRoute: PasteIdDiffRoute,
  PasteIdModuleRoute: PasteIdModuleRoute,
  PasteIdRawRoute: PasteIdRawRoute,
  PasteIdIndexRoute: PasteIdIndexRoute,
}

const PasteIdRouteWithChildren =
  PasteIdRoute._addFileChildren(PasteIdRouteChildren)

interface PasteRouteChildren {
  PasteIdRoute: typeof PasteIdRouteWithChildren
  PasteAllRoute: typeof PasteAllRoute
  PasteIndexRoute: typeof PasteIndexRoute
  PasteForkIdRoute: typeof PasteForkIdRoute
}

const PasteRouteChildren: PasteRouteChildren = {
  PasteIdRoute: PasteIdRouteWithChildren,
  PasteAllRoute: PasteAllRoute,
  PasteIndexRoute: PasteIndexRoute,
  PasteForkIdRoute: PasteForkIdRoute,
}

const PasteRouteWithChildren = PasteRoute._addFileChildren(PasteRouteChildren)

interface ThoughtsRouteChildren {
  ThoughtsIdRoute: typeof ThoughtsIdRoute
  ThoughtsBooksRoute: typeof ThoughtsBooksRoute
  ThoughtsEventsRoute: typeof ThoughtsEventsRoute
  ThoughtsLocationsRoute: typeof ThoughtsLocationsRoute
  ThoughtsMoviesRoute: typeof ThoughtsMoviesRoute
  ThoughtsMusicRoute: typeof ThoughtsMusicRoute
  ThoughtsProjectsRoute: typeof ThoughtsProjectsRoute
  ThoughtsQuestionsRoute: typeof ThoughtsQuestionsRoute
  ThoughtsTasksRoute: typeof ThoughtsTasksRoute
  ThoughtsIndexRoute: typeof ThoughtsIndexRoute
  ThoughtsFramingsIdRoute: typeof ThoughtsFramingsIdRoute
  ThoughtsTIdRoute: typeof ThoughtsTIdRoute
  ThoughtsFramingsIndexRoute: typeof ThoughtsFramingsIndexRoute
}

const ThoughtsRouteChildren: ThoughtsRouteChildren = {
  ThoughtsIdRoute: ThoughtsIdRoute,
  ThoughtsBooksRoute: ThoughtsBooksRoute,
  ThoughtsEventsRoute: ThoughtsEventsRoute,
  ThoughtsLocationsRoute: ThoughtsLocationsRoute,
  ThoughtsMoviesRoute: ThoughtsMoviesRoute,
  ThoughtsMusicRoute: ThoughtsMusicRoute,
  ThoughtsProjectsRoute: ThoughtsProjectsRoute,
  ThoughtsQuestionsRoute: ThoughtsQuestionsRoute,
  ThoughtsTasksRoute: ThoughtsTasksRoute,
  ThoughtsIndexRoute: ThoughtsIndexRoute,
  ThoughtsFramingsIdRoute: ThoughtsFramingsIdRoute,
  ThoughtsTIdRoute: ThoughtsTIdRoute,
  ThoughtsFramingsIndexRoute: ThoughtsFramingsIndexRoute,
}

const ThoughtsRouteWithChildren = ThoughtsRoute._addFileChildren(
  ThoughtsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  ShellRoute: ShellRouteWithChildren,
  ExploreRoute: ExploreRoute,
  LoginRoute: LoginRoute,
  PasteRoute: PasteRouteWithChildren,
  SearchRoute: SearchRoute,
  ThoughtsRoute: ThoughtsRouteWithChildren,
  ApiAttachmentsSplatRoute: ApiAttachmentsSplatRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiAuthDevLoginRoute: ApiAuthDevLoginRoute,
  ApiRindleMutateRoute: ApiRindleMutateRoute,
  ApiRindleQueryRoute: ApiRindleQueryRoute,
  ApiRindleReadRoute: ApiRindleReadRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
