name = "tantamanlands"
main = "src/index.ts"
compatibility_date = "2025-03-03"

[[kv_namespaces]]
binding = "EMBEDDINGS"
id = "c616f080e03e4c1292ff8004b93cbd0b"

[ai]
binding = "AI"

[[d1_databases]]
binding = "DB"
database_name = "thought"
database_id = "<from wrangler d1 create>"

[vars]
THOUGHT_SECRET = "<your-secret>"
