name = "tantamanlands"
main = "src/index.ts"
compatibility_date = "2025-03-03"

[[kv_namespaces]]
binding = "EMBEDDINGS"
id = "c616f080e03e4c1292ff8004b93cbd0b"

[ai]
binding = "AI"

[[d1_databases]]
binding = "DB"
database_name = "thought"
database_id = "a1190a47-fe1e-4fdb-8d7a-06dd5714fc6b"

[[r2_buckets]]
binding = "BUCKET"
bucket_name = "thought-attachments"

[observability]
[observability.logs]
enabled = false
invocation_logs = true
